### ISSUE TITLE
Difference between target and actual also handled in gait scheduler/controller

### ISSUE THREAD

**Issue by TimBuckers** [project-march/hardware-interface#149] opened 2019-09-01 11:13 UTC
The controller already throws an error when the difference between path (target) and actual is too big. This is now handled by the scheduler node, by freezing (see https://github.com/project-march/march-iv/pull/340). However, in position mode this check is also done in the hardware-interface. This is handled by crashing the hardware interface (not freezing).

Possible solutions:
- [ ] remove this check entirely from hardware interface. This is not perfect, because this check adds safety, however this makes the behavior more consistent between position and torque mode.
- [x] make the check in the controller more restrict than the hardware interface check (this means freeze first and crash only when it becomes worse). So probably make the 0.27 rad in the hardware interface larger not the 0.27 smaller in the controller, because the 0.27 is already causing many crashes on trainings.

**Comment by martijnvandermarel** [comment] 2019-09-01 18:40
I would go for the second one for the next training and see if it works as intended. Seems relatively easy

**Comment by JitskedeVries** [comment] 2019-09-01 19:42
I agree with Martijn. We shouldn't remove the extra safety. (Altough in Torque Mode there is no extra safety.)

**Comment by Olavhaasie** [comment] 2019-09-24 14:33
This has been fixed in #150

**Closed as completed by Olavhaasie** 2019-09-24 14:33 UTC
Labels: Could
